# -*- coding: utf-8 -*-
"""Practise GenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baodMEjo3JBvZolB8HY6y5RRs_DsttiL
"""

// artificial neural network

import numpy as np
def sigmoid(x):
  return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
  return x*(1-x)
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

print(y)

// GAN

import numpy as np
import tensorflow.keras models as Sequential
import tensorflow.keras layers as Dense
import tensorflow.keras optimizers as Adam

def Generator():
  model = Sequential()
  model.add = (Dense(16, activation = 'relu' , input_dim = 5))
  model.add = (Dense(1, activation = 'linear' ))
  model.compile(loss = 'mean_squared_error', optimizer = Adam(lr = 0.001))
  return model

def Discriminator():
  model = Sequential()
  model.add = (Dense(16, activation = 'relu' , input_dim = 5))
  model.add = (Dense(1, activation = 'linear' ))
  model.compile(loss = 'mean_squared_error', optimizer = Adam(lr = 0.001))
  return model

  generator = Generator()
  discriminator = Discriminator()

def GAN(generator, discriminator):
    model = Sequential()
    model.add(generator)

  discriminator.trainable = False
  gan = Sequential([generator, dicriminator])
  gan.compile(loss = 'mean_squared_error', optimizer = Adam(lr = 0.001))

  real_data

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# ---------------------
# Build Generator
# ---------------------
def build_generator():
    model = Sequential()
    model.add(Dense(16, activation='relu', input_dim=5))
    model.add(Dense(1, activation='linear'))
    return model

# ---------------------
# Build Discriminator
# ---------------------
def build_discriminator():
    model = Sequential()
    model.add(Dense(16, activation='relu', input_dim=1))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])
    return model

# Create models
generator = build_generator()
discriminator = build_discriminator()

# Combine GAN
discriminator.trainable = False
gan = Sequential([generator, discriminator])
gan.compile(loss='binary_crossentropy', optimizer=Adam())

# ---------------------
# Training
# ---------------------
for epoch in range(1000):

    # Real data (numbers around 1)
    real_data = np.random.normal(1, 0.1, (16,1))
    real_labels = np.ones((16,1))

    # Fake data
    noise = np.random.normal(0,1,(16,5))
    fake_data = generator.predict(noise, verbose=0)
    fake_labels = np.zeros((16,1))

    # Train Discriminator
    discriminator.trainable = True
    discriminator.train_on_batch(real_data, real_labels)
    discriminator.train_on_batch(fake_data, fake_labels)

    # Train Generator
    noise = np.random.normal(0,1,(16,5))
    valid_labels = np.ones((16,1))

    discriminator.trainable = False
    gan.train_on_batch(noise, valid_labels)

# Test Generator
noise = np.random.normal(0,1,(5,5))
generated = generator.predict(noise)

print("Generated Data:")
print(generated)

