# -*- coding: utf-8 -*-
"""Test_prac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyC64UgQ9FTzuANeEzbppQ2Qm0aybbmL
"""

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models

# Load pretrained model (without top layer)
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))

# Freeze base layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom classifier
x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation='relu')(x)
output = layers.Dense(10, activation='softmax')(x)

model = models.Model(inputs=base_model.input, outputs=output)

# Compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

import numpy as np
import tensorflow as tf

text = "hello world"

# Character mapping
chars = sorted(list(set(text)))
char_to_idx = {c:i for i,c in enumerate(chars)}
idx_to_char = {i:c for c,i in char_to_idx.items()}

# Prepare data
X = []
y = []

for i in range(len(text)-1):
    X.append(char_to_idx[text[i]])
    y.append(char_to_idx[text[i+1]])

X = np.array(X)
y = np.array(y)

# Model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(chars), 8),
    tf.keras.layers.SimpleRNN(32),
    tf.keras.layers.Dense(len(chars), activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

model.fit(X, y, epochs=100)

# Predict next char
pred = model.predict(np.array([char_to_idx['h']]))
print(idx_to_char[np.argmax(pred)])

import tensorflow as tf
import numpy as np

text = "deep learning is powerful "

chars = sorted(set(text))
char2idx = {c:i for i,c in enumerate(chars)}
idx2char = {i:c for c,i in char2idx.items()}

seq_length = 5
X, y = [], []

for i in range(len(text)-seq_length):
    X.append([char2idx[c] for c in text[i:i+seq_length]])
    y.append(char2idx[text[i+seq_length]])

X = np.array(X)
y = np.array(y)

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(chars), 16),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(len(chars), activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
model.fit(X, y, epochs=100)

# Generate text
input_seq = X[0]
for _ in range(20):
    pred = model.predict(np.array([input_seq]))
    next_char = np.argmax(pred)
    print(idx2char[next_char], end="")
    input_seq = np.append(input_seq[1:], next_char)

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

result = generator("Artificial Intelligence is", max_length=50)
print(result[0]['generated_text'])

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = "A futuristic city at sunset"
image = pipe(prompt).images[0]

image.save("output.png")

from PIL import Image
import cv2

img = cv2.imread("low_res.jpg")
upscaled = cv2.resize(img, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)

cv2.imwrite("high_res.jpg", upscaled)

import openai

openai.api_key = "YOUR_API_KEY"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role":"user","content":"Hello!"}]
)

print(response['choices'][0]['message']['content'])

import streamlit as st
import openai

openai.api_key = "YOUR_API_KEY"

st.title("AI Chatbot")

user_input = st.text_input("You:")

if user_input:
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role":"user","content":user_input}]
    )
    st.write(response['choices'][0]['message']['content'])

